### ISSUE TITLE
Group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by brenoxav** [brenoxav/pokemon-tcg#21]
### Group capstone: set up your Kanban board

https://github.com/brenoxav/pokemon-tcg/projects/1

There are 3 people in our team.

**Comment by Dipeshtwis** [comment]
# Status: Approved ✔️

## Hi Team :clap:  

Good job on implementing all the checklists. Well Done.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**You may close this Issue**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.
_**Dipesh Kumar**_

--------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by brenoxav** [comment]
Thank you, @Dipeshtwis!
